### ISSUE TITLE
Update release note and version

### ISSUE THREAD

**Issue by ross-spencer** [wellcomecollection/python-gearman#14]
Hi Alex, thanks for the recognition on your release note. If possible, can you add Artefactual Systems Inc. as well, as it was completed as part of the Archivematica work. 

I notice too, the version number was dropped back to `0.1.0`. I feel a minor bump was warranted where `0.1.0` didn't quite work as a drop-in replacement. This might have been an automated change? 

Ref: https://github.com/wellcomecollection/python-gearman/commit/63b7effe80e55dcdd9872cb9a7497fec2e5be599#diff-0270959f3dd5fb3637134fc695ecd521

**Comment by alexwlchan** [comment]
Will do! And yes, the version regression was deliberate – *in theory*, the automatic releasing tool will re-bump that 0.2.0 when it releases.

Something has gone wrong with the automatic releases which I need to look into…

**Comment by alexwlchan** [comment]
New release is finally up! https://github.com/wellcomecollection/python-gearman/blob/master/changes.rst
