### ISSUE TITLE
_unpack command check for NULL byte will always fail

### ISSUE THREAD

**Issue by ross-spencer** [wellcomecollection/python-gearman#9]
0eb378ec5c8ab5163d4311e82c4b445ddcb172f6 introduced an array change from c-type char; python character to c-type unsigned char; python int but a comparable change wasn't made later on in the code [here](https://github.com/wellcometrust/python-gearman/blob/46b1ecfcd1360f5c0daabfb88b3ac0f3c775e140/gearman/connection.py#L211) where the value at pos [0] (type: nt) is now being compared to a byte. This check would never pass now.  

I've demonstrated a Python 2/Python 3 fix [here](https://github.com/ross-spencer/python-gearman/commit/dcf4d7ef69bc4e280838330ba9c2dcdd7a7516af).

**Ref:** https://www.delftstack.com/howto/python/how-to-convert-int-to-bytes-in-python-2-and-python-3/

I am currently attempting to perform integration testing with Archivematica using our simple rpc client [mcp-rpc-cli](https://github.com/artefactual/archivematica-devtools/blob/master/tools/mcp-rpc-cli).

**Comment by alexwlchan** [comment]
Oops, thanks for flagging!

It looks like there were never any tests for that part of the code; I'll have a look now.

**Comment by ross-spencer** [comment]
Closing as should be resolved by https://github.com/wellcomecollection/python-gearman/pull/13
